version: '3.4'

services:

  redis:
    image: redis:alpine

  masa.auth.database:
     image: mcr.microsoft.com/mssql/server:2019-latest
     ports:
       - "1433:1433"
     environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y

  masa.auth.web.admin:
    image: ${DOCKER_REGISTRY-}masaauthwebadmin
    build:
      context: .
      dockerfile: src/Web/Masa.Auth.Web.Admin.Server/Dockerfile

  masa.auth.service.admin:
    image: ${DOCKER_REGISTRY-}masaauthservice
    build:
      context: .
      dockerfile: src/Services/masa.Auth.Service.Admin/Dockerfile

  
  dapr-placement:
    image: "daprio/dapr:1.5.1"